language: node_js
node_js:
    - "10.16.0"

branches:
    only: master

before_script:
    - cd test-app
    - npm install -g
    - npm install -g @angular/cli
    - npm install --save-dev @angular-devkit/build-angular

script:
    - ng lint
    - ng build
