language: node_js
node_js:
    - "10.16.0"

branches:
    only: master

before_script:
    - npm install -g @angular/cli
    - npm install --save-dev @angular-devkit/build-angular

script:
    - ng lint
    - ng build
    - ng test --watch=false --browsers=ChromeHeadless

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
