language: node_js
node_js:
    - "10.16.0"

branches:
    only: master

cache:
    directories:
        - dist/test-app

before_script:
    - npm install -g @angular/cli

jobs:
    include:
        - stage: Build
          script:
              - ng lint
              - ng build --prod --base-href https://arpanm96.github.io/angular-ci/
        - stage: Test
          name: Unit Test
          script: ng test --watch=false --browsers=ChromeHeadless
        - stage: Test
          name: Functional Test
          script: ng e2e
        - stage: Deploy
          script: echo "Deploying to https://arpanm96.github.io/angular-ci/"
          deploy:
              provider: pages
              skip_cleanup: true
              github_token: $GITHUB_TOKEN
              local_dir: dist/test-app
              on:
                  branch: master
