trigger:
    - master

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build_job
        pool:
            vmImage: "ubuntu-latest"
        steps:
            - checkout: self
              persistCredentials: 'true'
            - task: NodeTool@0
              inputs:
                  versionSpec: "11.0.0"
              displayName: Install Node.js
            - script: npm install -g @angular/cli
              displayName: Install Angular CLI
            - script: npm install
              displayName: Install NPM packages
            - script: ng lint
              displayName: Check lint
            - script: ng build --prod --base-href https://arpanm96.github.io/angular-ci/ 
              displayName: Build angular project
            - script: ng test --watch=false --browsers=ChromeHeadless
              displayName: Unit Test
            - script: ng e2e
              displayName: Functional Test
            - task: CopyFiles@2
              inputs:
                SourceFolder: '$(System.DefaultWorkingDirectory)'
                Contents: |
                  dist/test-app/*
                  package.json
                TargetFolder: '$(Build.ArtifactStagingDirectory)'
            - task: PublishBuildArtifacts@1
              inputs: 
                PathtoPublish: '$(Build.ArtifactStagingDirectory)'
                ArtifactName: TestApp

  - stage: deploy
    jobs:
      - job: deploy_job
        steps:
          - task: ShellScript@2
            inputs:
              scriptPath: ./deploy.sh
