trigger:
    - master

jobs:
    - job: build
      pool:
          vmImage: "ubuntu-latest"
          workspaces: 
            clean: outputs
      steps:
          - task: NodeTool@0
            inputs:
                versionSpec: "11.0.0"
            displayName: Install Node.js
          - script: npm install -g @angular/cli
            displayName: Install Angular CLI
          - script: npm install
            displayName: Install NPM packages
          - script: ng lint
            displayName: Check lint
          - script: ng build --prod
            displayName: Build angular project
    - job: unit_test
      dependsOn: build
      steps:
          - script: ng test --watch=false --browsers=ChromeHeadless
            displayName: Unit Test
    - job: e2e_test
      dependsOn: build
      steps:
          - script: ng e2e
            displayName: Functional Test
