trigger:
    - master

pool:
    vmImage: "ubuntu-latest"

jobs:
    - job: install_npm
      steps:
          - task: NodeTool@0
            inputs:
                versionSpec: "11.0.0"
            displayName: Install Node.js
    - job: build_node_modules
      steps:
          - script: npm install -g @angular/cli
            displayName: Install Angular CLI
          - script: npm install
            displayName: Install NPM packages
    - job: build_project
      steps:
          - script: ng lint
            displayName: Check lint
          - script: ng build --prod
            displayName: Build angular project
    - job: unit_test
      steps:
          - script: ng test --watch=false --browsers=ChromeHeadless
            displayName: Unit Test
    - job: e2e_test
      steps:
          - script: ng e2e
            displayName: Functional Test
