trigger:
    - master

pool:
    vmImage: "ubuntu-latest"

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: "11.0.0"
      displayName: "Install Node.js"

    - script: |
          npm install -g @angular/cli
          npm install
      displayName: "Build NPM"

    - script: |
          ng build --prod
      displayName: Build angular project
